#!/bin/bash
set -e
set -x

PYTHON_VERSION=`python -c "import sys;print(sys.version_info[0])"`

if [[ ${PYTHON_VERSION} == '3' ]];
then
    sudo rm -rf /usr/bin/python
    sudo ln -s /usr/bin/python3.4 /usr/bin/python
fi

sudo ./tools/travis/production-helper
